version: "3.7"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
      - ./:/tmp
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.dev
    depends_on:
      - database
    networks:
      - default
    ports:
    - "8080:8080"
volumes:
  data: